### ISSUE TITLE
Quickstart Guide to LocoKit2

### ISSUE THREAD

**Issue by califlower** [sobri909/LocoKit2#1] opened 2024-10-01 00:50 UTC
I know this is a pretty new library (and a big WIP, and simultaneously mostly used for yourself), but if possible a quickstart guide would be very helpful whenever you get a chance.. 

The way I've set it up, I 
- start the timeline recorder which starts the locomotion manager. 
- I use the TimelineSegment to retrieve stored ranges.
- I confirm the activity types for trip items
- I then queue them up and create a model from that as a background process. 

if you want, I can make a PR with what I've learned, but there's still some pieces missing. For example there's a lot of visits that seem to overlap each other consecutively with nearly the same latitude and longtitude. Not sure how to get those to auto merge or train the model to make those the same visit?. Also if I want to get certain things to not be classified as a visit, not sure how to train that either

**Comment by sobri909** [comment] 2024-10-01 02:51
Hi @califlower!

I eventually want to make public a repo for one of the apps using LocoKit2, like how the public Arc Mini repo acts as example code for old LocoKit. But for now the main repo using LocoKit2 is still very chaotic and not really trustworthy enough for public consumption. 

But it sounds like you've managed to start hooking up all of the subsystems! Looks like your code is probably around the same level as my main private repo using LocoKit2. I've only just today hooked up some UI for setting confirmedActivityType on the samples in ItemSegments, but haven't successfully used that to build any Core ML models yet (though that code looks to me like it *should* work fine - it's just still untested on my side). 

For the timeline linked list being a bit messy, currently TimelineRecorder will run the processor over it when going into sleep mode, from currentItem back in time a bit. And TimelineSegment can be told to reprocess on every update (shouldReprocessOnUpdate), which I'm doing for the segments I use for the UI. That will reprocess all the items in the segment, so achieves more thorough cleanup.

> Not sure how to get those to auto merge or train the model to make those the same visit?

I'm currently building out UI in my repo for helping this process along. One of the ways that Arc Timeline app achieves better merging of Visits is by having Places assigned to them. For example if there's "Home -> walking -> Home" and the walking is too brief to reach the isWorthKeeping threshold, then it can know to merge those together into a single Home visit.

Though the merge rules should already be taking care of "Visit -> walking -> Visit" in cases where the walking all falls inside the radius of either one of the visits or both combined. But I'm not seeing that happen yet, so maybe I haven't hooked back up one of the merge rules. (MergeScores is copied over from old LocoKit, so it's all the same merge rules as the old lib, but I haven't thoroughly tested them all yet to make sure they're behaving as expected in the new codebase).

One way that Arc Timeline app allows for manual cleanup of those "Visit -> brief Trip -> Visit" situations is with UI for converting the Trip to stationary type, which then turns that into a Visit item instead, thus facilitating the merge. But LocoKit2 doesn't have that code in yet, so even if you set the confirmedActivityType of the samples in the Trip to stationary it'll still be sitting there as a Trip item - not so useful yet. I'm hoping to get that code in today/tomorrow.

I'm basically playing whack-a-mole with the same things you're running into. As I see each bit of nonsense in the timeline I'm going in and either building some app UI to allow for manual cleanup, ie same as in Arc Timeline app's UI, or I'm finding where the existing processing/merge/etc code isn't doing what it should. I suspect there's still some cases of the latter, because some things in the timelines look like they surely should've been cleaned up in processing already.

**Comment by sobri909** [comment] 2024-10-01 03:02
Oh, on the issue of Places assigned to visits: old LocoKit never got that code. It was all only private in the Arc Timeline app repo. No wait, it must also be in the Arc Mini repo which is public. But either way, it never got migrated upstream to LocoKit. 

This time I'm building that into LocoKit2 directly, because it's pretty core, and does play a part in merge rules and has a bunch of side effects that change how Visits behave. But right now that code is ... yeah, effectively only stubbed up as a model struct and nothing more.

I'm excited to get that ported over and hooked up soon though. Once you can create Places and assign them to Visits the timeline really comes alive and starts to make a lot more sense. 

I think first I want to finish getting activityTypes all hooked up, with models getting built and classification happening as it should. Purely because I want to see proper activityType colours on my map view 😂 Though those type assignments can have an impact on merge rules too, so they're also more than just visual sugar.

Then once that's looking solid I'll get the Places system hooked up, and I think that'll be basically all of the core systems in place. I think beyond that everything else is auxiliary.

**Comment by califlower** [comment] 2024-10-01 16:03
AhH thank you for your thorough answer!! Seems like we're all bumping into the same stuff as we work on things. This library is way easier to use than the old one so I also really appreciate that, even if it's not done

Since I walk a lot in NYC, I'm testing out a lot of the parts of it (while simultaneously learning iOS development). But yeah like you said, I don't think the merges on visits is happening currently. I'm noticing a lot of home -> walk -> home with overlapping visits. Also a lot of visits being triggered for stop lights. But either way, very excited to see where you take this. It's super fun to play with.

**Closed as completed** 2024-10-01 16:04 UTC

**Comment by sobri909** [comment] 2024-10-02 03:57
> But yeah like you said, I don't think the merges on visits is happening currently. I'm noticing a lot of home -> walk -> home with overlapping visits. Also a lot of visits being triggered for stop lights.

I'm also seeing a lot of brief visits still appearing in the timeline long after they should've been merged, ie ones that don't meet the isWorthKeeping threshold, so should always have a MergeScore above .impossible and always eventually get merged.

My hunch yesterday was that either the merges *have* happened and Arc Editor's UI (the app I'm using as testbed for LocoKit2) isn't updating on view model change, or TimelineSegment isn't reprocessing the items correctly somehow. Because I added a debug button in my UI that fires off: 

```swift
let items = viewModel.selectedPageViewModel.timelineItems 
await TimelineProcessor.highlander.process(items)
```

(Where timelineItems is the items directly from the TimelineSegment), and that button is cleaning up the non-keeper items (after I page around the UI a bit to definitely trigger the necessary view updates - SwiftUI isn't being entirely friendly yet).

So it looks to me like the merge rules *are* being correctly applied, but... eh, I'll keep digging.

I'm also in the process of reworking/rethinking how TimelineSegment does sample reclassification and reprocessing, and whether it's even appropriate for TimelineSegment to be doing that. (It does optionally do that in old LocoKit, and Arc Timeline app depends on it pretty heavily. But old LocoKit is a decade's worth of cruft and long forgotten decisions, so I'm reassessing all of its behaviours as I port them across).

Eh, hopefully I'll figure this one out today. It's been bothering me for a few days now, as I build out various bits of UI around it.
